/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogomemoria.gui;

import jogomemoria.control.JogoMemoriaCtrl;
import jogomemoria.model.PecaTabuleiro;

/**
 *
 * @author Aluno
 */
public class TabuleiroNivelProfissional extends javax.swing.JPanel {
    
private JogoMemoriaCtrl controle;
  
    
    
    int pecasSelecionadas = 0;
    
    PecaTabuleiro pt1, pt2;
    
    
    public TabuleiroNivelProfissional() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblImg00 = new javax.swing.JLabel();
        lblImg01 = new javax.swing.JLabel();
        lblImg02 = new javax.swing.JLabel();
        lblImg03 = new javax.swing.JLabel();
        lblImg04 = new javax.swing.JLabel();
        lblImg05 = new javax.swing.JLabel();
        lblImg06 = new javax.swing.JLabel();
        lblImg07 = new javax.swing.JLabel();
        lblImg08 = new javax.swing.JLabel();
        lblImg10 = new javax.swing.JLabel();
        lblImg11 = new javax.swing.JLabel();
        lblImg12 = new javax.swing.JLabel();
        lblImg13 = new javax.swing.JLabel();
        lblImg14 = new javax.swing.JLabel();
        lblImg15 = new javax.swing.JLabel();
        lblImg16 = new javax.swing.JLabel();
        lblImg17 = new javax.swing.JLabel();
        lblImg18 = new javax.swing.JLabel();
        lblImg20 = new javax.swing.JLabel();
        lblImg21 = new javax.swing.JLabel();
        lblImg22 = new javax.swing.JLabel();
        lblImg23 = new javax.swing.JLabel();
        lblImg24 = new javax.swing.JLabel();
        lblImg25 = new javax.swing.JLabel();
        lblImg26 = new javax.swing.JLabel();
        lblImg27 = new javax.swing.JLabel();
        lblImg28 = new javax.swing.JLabel();
        lblImg30 = new javax.swing.JLabel();
        lblImg31 = new javax.swing.JLabel();
        lblImg32 = new javax.swing.JLabel();
        lblImg33 = new javax.swing.JLabel();
        lblImg34 = new javax.swing.JLabel();
        lblImg35 = new javax.swing.JLabel();
        lblImg36 = new javax.swing.JLabel();
        lblImg37 = new javax.swing.JLabel();
        lblImg38 = new javax.swing.JLabel();
        lblImg40 = new javax.swing.JLabel();
        lblImg41 = new javax.swing.JLabel();
        lblImg42 = new javax.swing.JLabel();
        lblImg43 = new javax.swing.JLabel();
        lblImg44 = new javax.swing.JLabel();
        lblImg45 = new javax.swing.JLabel();
        lblImg46 = new javax.swing.JLabel();
        lblImg47 = new javax.swing.JLabel();
        lblImg48 = new javax.swing.JLabel();
        lblImg50 = new javax.swing.JLabel();
        lblImg51 = new javax.swing.JLabel();
        lblImg52 = new javax.swing.JLabel();
        lblImg53 = new javax.swing.JLabel();
        lblImg54 = new javax.swing.JLabel();
        lblImg55 = new javax.swing.JLabel();
        lblImg56 = new javax.swing.JLabel();
        lblImg57 = new javax.swing.JLabel();
        lblImg58 = new javax.swing.JLabel();

        setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setLayout(new java.awt.GridLayout(6, 9));

        lblImg00.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg00MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg00);

        lblImg01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg01MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg01);

        lblImg02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg02MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg02);

        lblImg03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg03MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg03);

        lblImg04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg04MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg04);

        lblImg05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg05MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg05);

        lblImg06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg06MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg06);

        lblImg07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg07.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg07MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg07);

        lblImg08.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg08.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg08MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg08);

        lblImg10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg10MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg10);

        lblImg11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg11MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg11);

        lblImg12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg12MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg12);

        lblImg13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg13MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg13);

        lblImg14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg14MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg14);

        lblImg15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg15MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg15);

        lblImg16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg16MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg16);

        lblImg17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg17MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg17);

        lblImg18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg18MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg18);

        lblImg20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg20MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg20);

        lblImg21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg21MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg21);

        lblImg22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg22MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg22);

        lblImg23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg23MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg23);

        lblImg24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg24MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg24);

        lblImg25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg25MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg25);

        lblImg26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg26MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg26);

        lblImg27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg27MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg27);

        lblImg28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg28MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg28);

        lblImg30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg30MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg30);

        lblImg31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg31MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg31);

        lblImg32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg32MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg32);

        lblImg33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg33MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg33);

        lblImg34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg34MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg34);

        lblImg35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg35MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg35);

        lblImg36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg36MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg36);

        lblImg37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg37MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg37);

        lblImg38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg38MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg38);

        lblImg40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg40MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg40);

        lblImg41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg41MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg41);

        lblImg42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg42MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg42);

        lblImg43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg43MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg43);

        lblImg44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg44MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg44);

        lblImg45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg45MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg45);

        lblImg46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg46.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg46MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg46);

        lblImg47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg47.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg47MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg47);

        lblImg48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg48.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg48MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg48);

        lblImg50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg50MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg50);

        lblImg51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg51.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg51MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg51);

        lblImg52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg52.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg52MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg52);

        lblImg53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg53.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg53MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg53);

        lblImg54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg54.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg54MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg54);

        lblImg55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg55.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg55MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg55);

        lblImg56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg56.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg56MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg56);

        lblImg57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg57.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg57MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg57);

        lblImg58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"))); // NOI18N
        lblImg58.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImg58MouseClicked(evt);
            }
        });
        jPanel1.add(lblImg58);

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void lblImg00MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg00MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg00MouseClicked

    private void lblImg01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg01MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg01MouseClicked

    private void lblImg02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg02MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg02MouseClicked

    private void lblImg03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg03MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg03MouseClicked

    private void lblImg04MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg04MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg04MouseClicked

    private void lblImg05MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg05MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg05MouseClicked

    private void lblImg06MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg06MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg06MouseClicked

    private void lblImg07MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg07MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg07MouseClicked

    private void lblImg08MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg08MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg08MouseClicked

    private void lblImg10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg10MouseClicked

    private void lblImg11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg11MouseClicked

    private void lblImg12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg12MouseClicked

    private void lblImg13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg13MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg13MouseClicked

    private void lblImg14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg14MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg14MouseClicked

    private void lblImg15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg15MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg15MouseClicked

    private void lblImg16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg16MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg16MouseClicked

    private void lblImg17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg17MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg17MouseClicked

    private void lblImg18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg18MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg18MouseClicked

    private void lblImg20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg20MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg20MouseClicked

    private void lblImg21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg21MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg21MouseClicked

    private void lblImg22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg22MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg22MouseClicked

    private void lblImg23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg23MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg23MouseClicked

    private void lblImg24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg24MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg24MouseClicked

    private void lblImg25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg25MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg25MouseClicked

    private void lblImg26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg26MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg26MouseClicked

    private void lblImg27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg27MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg27MouseClicked

    private void lblImg28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg28MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg28MouseClicked

    private void lblImg30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg30MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg30MouseClicked

    private void lblImg31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg31MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg31MouseClicked

    private void lblImg32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg32MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg32MouseClicked

    private void lblImg33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg33MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg33MouseClicked

    private void lblImg34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg34MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg34MouseClicked

    private void lblImg35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg35MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg35MouseClicked

    private void lblImg36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg36MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg36MouseClicked

    private void lblImg37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg37MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg37MouseClicked

    private void lblImg38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg38MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg38MouseClicked

    private void lblImg40MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg40MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg40MouseClicked

    private void lblImg41MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg41MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg41MouseClicked

    private void lblImg42MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg42MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg42MouseClicked

    private void lblImg43MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg43MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg43MouseClicked

    private void lblImg44MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg44MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg44MouseClicked

    private void lblImg45MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg45MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg45MouseClicked

    private void lblImg46MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg46MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg46MouseClicked

    private void lblImg47MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg47MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg47MouseClicked

    private void lblImg48MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg48MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg48MouseClicked

    private void lblImg50MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg50MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg50MouseClicked

    private void lblImg51MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg51MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg51MouseClicked

    private void lblImg52MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg52MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg52MouseClicked

    private void lblImg53MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg53MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg53MouseClicked

    private void lblImg54MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg54MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg54MouseClicked

    private void lblImg55MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg55MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg55MouseClicked

    private void lblImg56MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg56MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg56MouseClicked

    private void lblImg57MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg57MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg57MouseClicked

    private void lblImg58MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImg58MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblImg58MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImg00;
    private javax.swing.JLabel lblImg01;
    private javax.swing.JLabel lblImg02;
    private javax.swing.JLabel lblImg03;
    private javax.swing.JLabel lblImg04;
    private javax.swing.JLabel lblImg05;
    private javax.swing.JLabel lblImg06;
    private javax.swing.JLabel lblImg07;
    private javax.swing.JLabel lblImg08;
    private javax.swing.JLabel lblImg10;
    private javax.swing.JLabel lblImg11;
    private javax.swing.JLabel lblImg12;
    private javax.swing.JLabel lblImg13;
    private javax.swing.JLabel lblImg14;
    private javax.swing.JLabel lblImg15;
    private javax.swing.JLabel lblImg16;
    private javax.swing.JLabel lblImg17;
    private javax.swing.JLabel lblImg18;
    private javax.swing.JLabel lblImg20;
    private javax.swing.JLabel lblImg21;
    private javax.swing.JLabel lblImg22;
    private javax.swing.JLabel lblImg23;
    private javax.swing.JLabel lblImg24;
    private javax.swing.JLabel lblImg25;
    private javax.swing.JLabel lblImg26;
    private javax.swing.JLabel lblImg27;
    private javax.swing.JLabel lblImg28;
    private javax.swing.JLabel lblImg30;
    private javax.swing.JLabel lblImg31;
    private javax.swing.JLabel lblImg32;
    private javax.swing.JLabel lblImg33;
    private javax.swing.JLabel lblImg34;
    private javax.swing.JLabel lblImg35;
    private javax.swing.JLabel lblImg36;
    private javax.swing.JLabel lblImg37;
    private javax.swing.JLabel lblImg38;
    private javax.swing.JLabel lblImg40;
    private javax.swing.JLabel lblImg41;
    private javax.swing.JLabel lblImg42;
    private javax.swing.JLabel lblImg43;
    private javax.swing.JLabel lblImg44;
    private javax.swing.JLabel lblImg45;
    private javax.swing.JLabel lblImg46;
    private javax.swing.JLabel lblImg47;
    private javax.swing.JLabel lblImg48;
    private javax.swing.JLabel lblImg50;
    private javax.swing.JLabel lblImg51;
    private javax.swing.JLabel lblImg52;
    private javax.swing.JLabel lblImg53;
    private javax.swing.JLabel lblImg54;
    private javax.swing.JLabel lblImg55;
    private javax.swing.JLabel lblImg56;
    private javax.swing.JLabel lblImg57;
    private javax.swing.JLabel lblImg58;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the lblImg00
     */
    public javax.swing.JLabel getLblImg00() {
        return lblImg00;
    }

    /**
     * @param lblImg00 the lblImg00 to set
     */
    public void setLblImg00(javax.swing.JLabel lblImg00) {
        this.lblImg00 = lblImg00;
    }

    /**
     * @return the lblImg01
     */
    public javax.swing.JLabel getLblImg01() {
        return lblImg01;
    }

    /**
     * @param lblImg01 the lblImg01 to set
     */
    public void setLblImg01(javax.swing.JLabel lblImg01) {
        this.lblImg01 = lblImg01;
    }

    /**
     * @return the lblImg02
     */
    public javax.swing.JLabel getLblImg02() {
        return lblImg02;
    }

    /**
     * @param lblImg02 the lblImg02 to set
     */
    public void setLblImg02(javax.swing.JLabel lblImg02) {
        this.lblImg02 = lblImg02;
    }

    /**
     * @return the lblImg03
     */
    public javax.swing.JLabel getLblImg03() {
        return lblImg03;
    }

    /**
     * @param lblImg03 the lblImg03 to set
     */
    public void setLblImg03(javax.swing.JLabel lblImg03) {
        this.lblImg03 = lblImg03;
    }

    /**
     * @return the lblImg04
     */
    public javax.swing.JLabel getLblImg04() {
        return lblImg04;
    }

    /**
     * @param lblImg04 the lblImg04 to set
     */
    public void setLblImg04(javax.swing.JLabel lblImg04) {
        this.lblImg04 = lblImg04;
    }

    /**
     * @return the lblImg05
     */
    public javax.swing.JLabel getLblImg05() {
        return lblImg05;
    }

    /**
     * @param lblImg05 the lblImg05 to set
     */
    public void setLblImg05(javax.swing.JLabel lblImg05) {
        this.lblImg05 = lblImg05;
    }

    /**
     * @return the lblImg06
     */
    public javax.swing.JLabel getLblImg06() {
        return lblImg06;
    }

    /**
     * @param lblImg06 the lblImg06 to set
     */
    public void setLblImg06(javax.swing.JLabel lblImg06) {
        this.lblImg06 = lblImg06;
    }

    /**
     * @return the lblImg07
     */
    public javax.swing.JLabel getLblImg07() {
        return lblImg07;
    }

    /**
     * @param lblImg07 the lblImg07 to set
     */
    public void setLblImg07(javax.swing.JLabel lblImg07) {
        this.lblImg07 = lblImg07;
    }

    /**
     * @return the lblImg08
     */
    public javax.swing.JLabel getLblImg08() {
        return lblImg08;
    }

    /**
     * @param lblImg08 the lblImg08 to set
     */
    public void setLblImg08(javax.swing.JLabel lblImg08) {
        this.lblImg08 = lblImg08;
    }

    /**
     * @return the lblImg10
     */
    public javax.swing.JLabel getLblImg10() {
        return lblImg10;
    }

    /**
     * @param lblImg10 the lblImg10 to set
     */
    public void setLblImg10(javax.swing.JLabel lblImg10) {
        this.lblImg10 = lblImg10;
    }

    /**
     * @return the lblImg11
     */
    public javax.swing.JLabel getLblImg11() {
        return lblImg11;
    }

    /**
     * @param lblImg11 the lblImg11 to set
     */
    public void setLblImg11(javax.swing.JLabel lblImg11) {
        this.lblImg11 = lblImg11;
    }

    /**
     * @return the lblImg12
     */
    public javax.swing.JLabel getLblImg12() {
        return lblImg12;
    }

    /**
     * @param lblImg12 the lblImg12 to set
     */
    public void setLblImg12(javax.swing.JLabel lblImg12) {
        this.lblImg12 = lblImg12;
    }

    /**
     * @return the lblImg13
     */
    public javax.swing.JLabel getLblImg13() {
        return lblImg13;
    }

    /**
     * @param lblImg13 the lblImg13 to set
     */
    public void setLblImg13(javax.swing.JLabel lblImg13) {
        this.lblImg13 = lblImg13;
    }

    /**
     * @return the lblImg14
     */
    public javax.swing.JLabel getLblImg14() {
        return lblImg14;
    }

    /**
     * @param lblImg14 the lblImg14 to set
     */
    public void setLblImg14(javax.swing.JLabel lblImg14) {
        this.lblImg14 = lblImg14;
    }

    /**
     * @return the lblImg15
     */
    public javax.swing.JLabel getLblImg15() {
        return lblImg15;
    }

    /**
     * @param lblImg15 the lblImg15 to set
     */
    public void setLblImg15(javax.swing.JLabel lblImg15) {
        this.lblImg15 = lblImg15;
    }

    /**
     * @return the lblImg16
     */
    public javax.swing.JLabel getLblImg16() {
        return lblImg16;
    }

    /**
     * @param lblImg16 the lblImg16 to set
     */
    public void setLblImg16(javax.swing.JLabel lblImg16) {
        this.lblImg16 = lblImg16;
    }

    /**
     * @return the lblImg17
     */
    public javax.swing.JLabel getLblImg17() {
        return lblImg17;
    }

    /**
     * @param lblImg17 the lblImg17 to set
     */
    public void setLblImg17(javax.swing.JLabel lblImg17) {
        this.lblImg17 = lblImg17;
    }

    /**
     * @return the lblImg18
     */
    public javax.swing.JLabel getLblImg18() {
        return lblImg18;
    }

    /**
     * @param lblImg18 the lblImg18 to set
     */
    public void setLblImg18(javax.swing.JLabel lblImg18) {
        this.lblImg18 = lblImg18;
    }

    /**
     * @return the lblImg20
     */
    public javax.swing.JLabel getLblImg20() {
        return lblImg20;
    }

    /**
     * @param lblImg20 the lblImg20 to set
     */
    public void setLblImg20(javax.swing.JLabel lblImg20) {
        this.lblImg20 = lblImg20;
    }

    /**
     * @return the lblImg21
     */
    public javax.swing.JLabel getLblImg21() {
        return lblImg21;
    }

    /**
     * @param lblImg21 the lblImg21 to set
     */
    public void setLblImg21(javax.swing.JLabel lblImg21) {
        this.lblImg21 = lblImg21;
    }

    /**
     * @return the lblImg22
     */
    public javax.swing.JLabel getLblImg22() {
        return lblImg22;
    }

    /**
     * @param lblImg22 the lblImg22 to set
     */
    public void setLblImg22(javax.swing.JLabel lblImg22) {
        this.lblImg22 = lblImg22;
    }

    /**
     * @return the lblImg23
     */
    public javax.swing.JLabel getLblImg23() {
        return lblImg23;
    }

    /**
     * @param lblImg23 the lblImg23 to set
     */
    public void setLblImg23(javax.swing.JLabel lblImg23) {
        this.lblImg23 = lblImg23;
    }

    /**
     * @return the lblImg24
     */
    public javax.swing.JLabel getLblImg24() {
        return lblImg24;
    }

    /**
     * @param lblImg24 the lblImg24 to set
     */
    public void setLblImg24(javax.swing.JLabel lblImg24) {
        this.lblImg24 = lblImg24;
    }

    /**
     * @return the lblImg25
     */
    public javax.swing.JLabel getLblImg25() {
        return lblImg25;
    }

    /**
     * @param lblImg25 the lblImg25 to set
     */
    public void setLblImg25(javax.swing.JLabel lblImg25) {
        this.lblImg25 = lblImg25;
    }

    /**
     * @return the lblImg26
     */
    public javax.swing.JLabel getLblImg26() {
        return lblImg26;
    }

    /**
     * @param lblImg26 the lblImg26 to set
     */
    public void setLblImg26(javax.swing.JLabel lblImg26) {
        this.lblImg26 = lblImg26;
    }

    /**
     * @return the lblImg27
     */
    public javax.swing.JLabel getLblImg27() {
        return lblImg27;
    }

    /**
     * @param lblImg27 the lblImg27 to set
     */
    public void setLblImg27(javax.swing.JLabel lblImg27) {
        this.lblImg27 = lblImg27;
    }

    /**
     * @return the lblImg28
     */
    public javax.swing.JLabel getLblImg28() {
        return lblImg28;
    }

    /**
     * @param lblImg28 the lblImg28 to set
     */
    public void setLblImg28(javax.swing.JLabel lblImg28) {
        this.lblImg28 = lblImg28;
    }

    /**
     * @return the lblImg30
     */
    public javax.swing.JLabel getLblImg30() {
        return lblImg30;
    }

    /**
     * @param lblImg30 the lblImg30 to set
     */
    public void setLblImg30(javax.swing.JLabel lblImg30) {
        this.lblImg30 = lblImg30;
    }

    /**
     * @return the lblImg31
     */
    public javax.swing.JLabel getLblImg31() {
        return lblImg31;
    }

    /**
     * @param lblImg31 the lblImg31 to set
     */
    public void setLblImg31(javax.swing.JLabel lblImg31) {
        this.lblImg31 = lblImg31;
    }

    /**
     * @return the lblImg32
     */
    public javax.swing.JLabel getLblImg32() {
        return lblImg32;
    }

    /**
     * @param lblImg32 the lblImg32 to set
     */
    public void setLblImg32(javax.swing.JLabel lblImg32) {
        this.lblImg32 = lblImg32;
    }

    /**
     * @return the lblImg33
     */
    public javax.swing.JLabel getLblImg33() {
        return lblImg33;
    }

    /**
     * @param lblImg33 the lblImg33 to set
     */
    public void setLblImg33(javax.swing.JLabel lblImg33) {
        this.lblImg33 = lblImg33;
    }

    /**
     * @return the lblImg34
     */
    public javax.swing.JLabel getLblImg34() {
        return lblImg34;
    }

    /**
     * @param lblImg34 the lblImg34 to set
     */
    public void setLblImg34(javax.swing.JLabel lblImg34) {
        this.lblImg34 = lblImg34;
    }

    /**
     * @return the lblImg35
     */
    public javax.swing.JLabel getLblImg35() {
        return lblImg35;
    }

    /**
     * @param lblImg35 the lblImg35 to set
     */
    public void setLblImg35(javax.swing.JLabel lblImg35) {
        this.lblImg35 = lblImg35;
    }

    /**
     * @return the lblImg36
     */
    public javax.swing.JLabel getLblImg36() {
        return lblImg36;
    }

    /**
     * @param lblImg36 the lblImg36 to set
     */
    public void setLblImg36(javax.swing.JLabel lblImg36) {
        this.lblImg36 = lblImg36;
    }

    /**
     * @return the lblImg37
     */
    public javax.swing.JLabel getLblImg37() {
        return lblImg37;
    }

    /**
     * @param lblImg37 the lblImg37 to set
     */
    public void setLblImg37(javax.swing.JLabel lblImg37) {
        this.lblImg37 = lblImg37;
    }

    /**
     * @return the lblImg38
     */
    public javax.swing.JLabel getLblImg38() {
        return lblImg38;
    }

    /**
     * @param lblImg38 the lblImg38 to set
     */
    public void setLblImg38(javax.swing.JLabel lblImg38) {
        this.lblImg38 = lblImg38;
    }

    /**
     * @return the lblImg40
     */
    public javax.swing.JLabel getLblImg40() {
        return lblImg40;
    }

    /**
     * @param lblImg40 the lblImg40 to set
     */
    public void setLblImg40(javax.swing.JLabel lblImg40) {
        this.lblImg40 = lblImg40;
    }

    /**
     * @return the lblImg41
     */
    public javax.swing.JLabel getLblImg41() {
        return lblImg41;
    }

    /**
     * @param lblImg41 the lblImg41 to set
     */
    public void setLblImg41(javax.swing.JLabel lblImg41) {
        this.lblImg41 = lblImg41;
    }

    /**
     * @return the lblImg42
     */
    public javax.swing.JLabel getLblImg42() {
        return lblImg52;
    }

    /**
     * @param lblImg42 the lblImg42 to set
     */
    public void setLblImg42(javax.swing.JLabel lblImg42) {
        this.lblImg52 = lblImg42;
    }

    /**
     * @return the lblImg43
     */
    public javax.swing.JLabel getLblImg43() {
        return lblImg42;
    }

    /**
     * @param lblImg43 the lblImg43 to set
     */
    public void setLblImg43(javax.swing.JLabel lblImg43) {
        this.lblImg42 = lblImg43;
    }

    /**
     * @return the lblImg44
     */
    public javax.swing.JLabel getLblImg44() {
        return lblImg43;
    }

    /**
     * @param lblImg44 the lblImg44 to set
     */
    public void setLblImg44(javax.swing.JLabel lblImg44) {
        this.lblImg43 = lblImg44;
    }

    /**
     * @return the lblImg45
     */
    public javax.swing.JLabel getLblImg45() {
        return lblImg44;
    }

    /**
     * @param lblImg45 the lblImg45 to set
     */
    public void setLblImg45(javax.swing.JLabel lblImg45) {
        this.lblImg44 = lblImg45;
    }

    /**
     * @return the lblImg46
     */
    public javax.swing.JLabel getLblImg46() {
        return lblImg45;
    }

    /**
     * @param lblImg46 the lblImg46 to set
     */
    public void setLblImg46(javax.swing.JLabel lblImg46) {
        this.lblImg45 = lblImg46;
    }

    /**
     * @return the lblImg47
     */
    public javax.swing.JLabel getLblImg47() {
        return lblImg46;
    }

    /**
     * @param lblImg47 the lblImg47 to set
     */
    public void setLblImg47(javax.swing.JLabel lblImg47) {
        this.lblImg46 = lblImg47;
    }

    /**
     * @return the lblImg48
     */
    public javax.swing.JLabel getLblImg48() {
        return lblImg47;
    }

    /**
     * @param lblImg48 the lblImg48 to set
     */
    public void setLblImg48(javax.swing.JLabel lblImg48) {
        this.lblImg47 = lblImg48;
    }

    /**
     * @return the lblImg50
     */
    public javax.swing.JLabel getLblImg50() {
        return lblImg48;
    }

    /**
     * @param lblImg50 the lblImg50 to set
     */
    public void setLblImg50(javax.swing.JLabel lblImg50) {
        this.lblImg48 = lblImg50;
    }

    /**
     * @return the lblImg51
     */
    public javax.swing.JLabel getLblImg51() {
        return lblImg50;
    }

    /**
     * @param lblImg51 the lblImg51 to set
     */
    public void setLblImg51(javax.swing.JLabel lblImg51) {
        this.lblImg50 = lblImg51;
    }

    /**
     * @return the lblImg52
     */
    public javax.swing.JLabel getLblImg52() {
        return lblImg51;
    }

    /**
     * @param lblImg52 the lblImg52 to set
     */
    public void setLblImg52(javax.swing.JLabel lblImg52) {
        this.lblImg51 = lblImg52;
    }

    /**
     * @return the lblImg53
     */
    public javax.swing.JLabel getLblImg53() {
        return lblImg53;
    }

    /**
     * @param lblImg53 the lblImg53 to set
     */
    public void setLblImg53(javax.swing.JLabel lblImg53) {
        this.lblImg53 = lblImg53;
    }

    /**
     * @return the lblImg54
     */
    public javax.swing.JLabel getLblImg54() {
        return lblImg54;
    }

    /**
     * @param lblImg54 the lblImg54 to set
     */
    public void setLblImg54(javax.swing.JLabel lblImg54) {
        this.lblImg54 = lblImg54;
    }

    /**
     * @return the lblImg55
     */
    public javax.swing.JLabel getLblImg55() {
        return lblImg55;
    }

    /**
     * @param lblImg55 the lblImg55 to set
     */
    public void setLblImg55(javax.swing.JLabel lblImg55) {
        this.lblImg55 = lblImg55;
    }

    /**
     * @return the lblImg56
     */
    public javax.swing.JLabel getLblImg56() {
        return lblImg56;
    }

    /**
     * @param lblImg56 the lblImg56 to set
     */
    public void setLblImg56(javax.swing.JLabel lblImg56) {
        this.lblImg56 = lblImg56;
    }

    /**
     * @return the lblImg57
     */
    public javax.swing.JLabel getLblImg57() {
        return lblImg57;
    }

    /**
     * @param lblImg57 the lblImg57 to set
     */
    public void setLblImg57(javax.swing.JLabel lblImg57) {
        this.lblImg57 = lblImg57;
    }

    /**
     * @return the lblImg58
     */
    public javax.swing.JLabel getLblImg58() {
        return lblImg58;
    }

    /**
     * @param lblImg58 the lblImg58 to set
     */
    public void setLblImg58(javax.swing.JLabel lblImg58) {
        this.lblImg58 = lblImg58;
    }
}
