/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogomemoria.gui;

import javax.swing.JSplitPane;

/**
 *
 * @author Aluno
 */
public class Tabuleiro extends javax.swing.JPanel {

    /**
     * Creates new form tabuleiro
     */
    public Tabuleiro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sppTabuleiro = new javax.swing.JSplitPane();
        tabuleiroNivelIniciante1 = new jogomemoria.gui.TabuleiroNivelIniciante();
        infos1 = new jogomemoria.gui.Infos();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        sppTabuleiro.setDividerLocation(600);
        sppTabuleiro.setLeftComponent(tabuleiroNivelIniciante1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("RECORDES");

        javax.swing.GroupLayout infos1Layout = new javax.swing.GroupLayout(infos1);
        infos1.setLayout(infos1Layout);
        infos1Layout.setHorizontalGroup(
            infos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infos1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        infos1Layout.setVerticalGroup(
            infos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infos1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(305, Short.MAX_VALUE))
        );

        sppTabuleiro.setRightComponent(infos1);

        add(sppTabuleiro, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    public JSplitPane getSPPTabuleiro() {
        return sppTabuleiro;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jogomemoria.gui.Infos infos1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane sppTabuleiro;
    private jogomemoria.gui.TabuleiroNivelIniciante tabuleiroNivelIniciante1;
    // End of variables declaration//GEN-END:variables
}
